---
- hosts: grafana
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - grafana

- hosts: alertmanager
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - alertmanager

- hosts: node_exporter
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - prometheus_node_exporter

- hosts: blackbox_exporter
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - prometheus_blackbox_exporter

- hosts: prometheus
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - prometheus

- hosts: telegram_bot
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - telegram

