global:
  slack_api_url: "https://hooks.slack.com/services/SlackWebhookAPI"

route:
  group_by: [alertname, datacenter, app]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 5m
  receiver: 'alert-team'

receivers:
- name: 'alert-team'
  slack_configs:
  - channel: "#webhook-test"
    text: "summary: {{ .CommonAnnotations.summary }}\ndescription: {{ .CommonAnnotations.description }}"
  webhook_configs:
    - send_resolved: True
      url: 'http://192.168.48.129:9087/alert/{{TelegramId}}'
